font=Jetbrains Mono:size=10

[colors]
# Dracula Background & Text
background=282a36ff
text=f8f8f2ff

# Pink Accents
match=ff79c6ff
selection=44475aff
selection-text=ff79c6ff
selection-match=f8f8f2ff
border=ff79c6ff

[border]
width=2
radius=12
