font=Jetbrains Mono:size=13, JetbrainsMono Nerd Font:size=13

[main]
include=/usr/share/foot/themes/tango

[key-bindings]
# Explicitly map URL open mode (O for Open)
show-urls-launch = Control+Shift+o
