preload = /home/markus/Downloads/wallpaper1HD.png
preload = /home/markus/Downloads/wallpaper1QHD.png
wallpaper = , /home/markus/Downloads/wallpaper1HD.png
wallpaper = desc:Philips Consumer Electronics Company PHL 346E2C UK02402015900, /home/markus/Downloads/wallpaper1QHD.png

